version: '3.9'
services:
  postgresservice:
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=cy_local_db_user
      - POSTGRES_PASSWORD=cy_local_db_pass
      - POSTGRES_DB=cy_local_db
  app:
    image: sleepingapp
    ports:
      - '3000:3000'
    depends_on:
      - postgresservice
    command: /bin/bash -c "sleep 10 && npm run pre-condition && npm run start"